package com.frame24.api.catalog.domain;

import com.frame24.api.catalog.infrastructure.repository.ProductCategoryRepository;
import com.frame24.api.catalog.infrastructure.repository.ProductRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest
@Transactional
public class ProductTest {

    @Autowired
    private ProductCategoryRepository categoryRepository;

    @Autowired
    private ProductRepository productRepository;

    @Test
    public void testSnowflakeIdGeneration() {
        // Create dependencies
        ProductCategory category = new ProductCategory();
        category.setName("Test Category");
        category.setCompanyId(1L);
        categoryRepository.save(category);

        // Create Product
        Product product = new Product();
        product.setCompanyId(1L);
        product.setCategory(category);
        product.setProductCode("TEST-001");
        product.setName("Test Product");

        // Save Product
        product = productRepository.save(product);
        productRepository.flush();

        // Verify ID generation
        assertNotNull(product.getId(), "Product ID should be generated by SnowflakeEntityListener");
        System.out.println("Generated Product ID: " + product.getId());
    }
}
